/**
 * compressed-static.ts
 *
 * Express middleware that serves the pre-compressed (brotli / gzip) variants of
 * static files generated by scripts/compress-dist.mjs.
 *
 * How it works:
 *   1. Inspect the client's Accept-Encoding header.
 *   2. If "br" is supported, try <file>.br → serve with Content-Encoding: br.
 *   3. Else if "gzip" supported, try <file>.gz → serve with Content-Encoding: gzip.
 *   4. Fall through to express.static which serves the uncompressed original.
 *
 * Cache strategy:
 *   - /js/* and /assets/*  → immutable, 1-year cache  (content-hashed filenames)
 *   - index.html           → no-cache  (must re-validate on every deploy)
 *   - everything else      → 1-hour cache
 *
 * Usage (in app.ts):
 *   import { compressedStatic } from './middlewares/compressed-static.js';
 *   const distDir = path.resolve('..', 'toon-rts', 'dist', 'public');
 *   app.use('/', compressedStatic(distDir));
 */

import fs          from 'node:fs';
import path        from 'node:path';
import type { Request, Response, NextFunction } from 'express';

// MIME types for pre-compressed file extensions
const MIME: Record<string, string> = {
  '.js':    'application/javascript; charset=utf-8',
  '.mjs':   'application/javascript; charset=utf-8',
  '.css':   'text/css; charset=utf-8',
  '.html':  'text/html; charset=utf-8',
  '.json':  'application/json; charset=utf-8',
  '.svg':   'image/svg+xml; charset=utf-8',
  '.xml':   'application/xml; charset=utf-8',
  '.txt':   'text/plain; charset=utf-8',
  '.map':   'application/json; charset=utf-8',
};

function cacheControl(urlPath: string): string {
  if (/\/index\.html?$/.test(urlPath) || urlPath === '/') {
    return 'no-cache, no-store, must-revalidate';
  }
  // Content-hashed assets (js/ and assets/) are safe for immutable caching
  if (/^\/(js|assets)\//.test(urlPath)) {
    return 'public, max-age=31536000, immutable';
  }
  return 'public, max-age=3600';
}

function acceptsEncoding(req: Request, encoding: string): boolean {
  const header = req.headers['accept-encoding'] ?? '';
  return header.split(',').some(e => e.trim().split(';')[0].trim() === encoding);
}

export function compressedStatic(distDir: string) {
  return function serveCompressed(req: Request, res: Response, next: NextFunction) {
    // Only handle GET / HEAD
    if (req.method !== 'GET' && req.method !== 'HEAD') return next();

    // Resolve the filesystem path
    let urlPath = req.path;
    if (urlPath === '/' || !path.extname(urlPath)) urlPath = '/index.html';

    const filePath = path.join(distDir, urlPath);
    const ext      = path.extname(filePath).toLowerCase();
    const mime     = MIME[ext];

    if (!mime) return next();                             // not a text asset → next()
    if (!fs.existsSync(filePath)) return next();         // file doesn't exist → next()

    res.setHeader('Cache-Control', cacheControl(urlPath));
    res.setHeader('Vary', 'Accept-Encoding');
    res.setHeader('Content-Type', mime);

    // Try brotli
    if (acceptsEncoding(req, 'br')) {
      const brPath = filePath + '.br';
      if (fs.existsSync(brPath)) {
        res.setHeader('Content-Encoding', 'br');
        res.setHeader('Content-Length', fs.statSync(brPath).size);
        return res.sendFile(brPath);
      }
    }

    // Try gzip
    if (acceptsEncoding(req, 'gzip')) {
      const gzPath = filePath + '.gz';
      if (fs.existsSync(gzPath)) {
        res.setHeader('Content-Encoding', 'gzip');
        res.setHeader('Content-Length', fs.statSync(gzPath).size);
        return res.sendFile(gzPath);
      }
    }

    // Uncompressed fallback
    res.setHeader('Content-Length', fs.statSync(filePath).size);
    res.sendFile(filePath);
  };
}
